class HomeController < ApplicationController
SPEAKERS =   [{:email => 'andrec@checkplant.com.br', :name => 'André Cantarelli & Frederico Fonseca', :company => 'checkplant.com.br', :bio => %(<b>André Cantarelli</b> Diretor da CheckPlant, Mestre em Ciência da Computação pela UFSC em 2005, e graduado pela UCPel em 2001, sempre tentou colocar em prática estudos e teorias, por isso, empreender foi sua escolha. Bastante envolvido com a área técnica, tem orgulho de sua equipe e acredita demais na CheckPlant.<br><br><b>Frederico Fonseca</b> Trabalha na CheckPlant Sistemas de Rastreabilidade, em Pelotas. Graduado em Tecnologia em Análise e Desenvolvimento de Sistemas pela UCPel em 2008, atua como desenvolvedor web utilizando PHP, MySQL, Ruby, Rails, BDD com Rspec, Apache, OpenVPN, Shell Script, Git, SVN, entre outros. Adepto e praticante das metodologias ágeis de desenvolvimento de software, como o XP. Usuário de Mac e de Ubuntu. Entusiasta e usuário de software livre.)},
  {:email => 'ccarneiroj@gmail.com', :name => 'Cloves Carneiro', :company => 'amazon.com', :bio => 'Aguardandio bio'},
  {:email => 'danicuki@gmail.com', :name => 'Daniel Cukier', :company => 'IME-USP', :bio => %(Daniel Cukier trabalha com desenvolvimento de software desde 1995, principalmente com Java e Ruby (Rails). É doutorando em Ciência da Computação pela Universidade de São Paulo, onde fez mestrado com a dissertação Padrões para Introduzir Novas Ideias na Indústria de Software (veja o vídeo). Ativo na comunidade ágil desde 2005, quando ingressou na Agilcoop, produzindo podcasts, artigos e ministrando cursos sobre agilidade. Introduziu o uso de Métodos Ágeis na Locaweb, maior empresa de hosting da America Latina, onde participou de vários projetos de software na área de SaaS e IaS. Organiza o evento DevOpsDays Brasil, um encontro de desenvolvedores com sysadmins. É autor do blog AgileAndArt, onde costuma escrever sobre as semelhanças entre desenvolvimento de software e as artes. Além da presença na área de software, trabalha com teatro, música (toca violão) e poesia.)},
  {:email => 'daniel@egenial.com.br', :name => 'Daniel Lopes', :company => 'objetiva.co', :bio => %(É sócio fundador da Objetiva Software e está envolvido com TI há quase uma década. Trabalha como desenvolvedor web com grande interesse em Ruby/TDD/Javascript e Frontend. Também é instrutor de treinamentos presenciais e online em parceria com a Egenial com mais de 500 alunos treinados em assuntos como Ruby e Rails. Também ministra a disciplina de Desenvolvimento Web em Pós Graduação na UNA e frequentemente participa da organização de eventos como Ruby Masters, Café Com TOM e Kata TOM. Formalmente é técnico e bacharel em Sistemas de Informação.)},
  {:email => 'diego@cuboxsa.com', :name => 'Diego Algorta*', :company => 'cubox.com.uy', :bio => 'Aguardandio bio'},
  {:email => 'everton.carpes@gmail.com', :name => 'Éverton Carpes', :company => 'globo.com', :bio => 'Aguardandio bio'},
  {:email => 'fabioakita@gmail.com', :name => 'Fábio Akita', :company => 'gonow.com.br', :bio => %(Fabio Akita é um conhecido blogueiro e evangelista da comunidade Ruby on Rails e Agile. Atualmente é Gerente de Projetos pela Gonow Tecnologia. Foi Gerente de Projetos na Locaweb, onde também fez parceria na concepção da conferência anual Rails Summit (rebatizada de "RubyConf Brasil"). Já trabalhou como Brazil Rails Practice Manager para a consultoria americana Surgeworks LLC. Por mais de 5 anos foi consultor de integração e desenvolvimento no mundo SAP. Tem mais de 15 anos de experiência nas áreas de desenvolvimento de software e gestão de projetos, dá palestras em faculdades e conferências de tecnologia e gestão)},
  {:email => 'felipe.lima@gmail.com', :name => 'Felipe Lima', :company => 'thoughtworks.com'},
  {:email => 'nicolas@quavio.com.br', :name => 'Nícolas Iensen', :company => 'quavio.com.br', :bio => %("Formado pela PUC-RS em Ciência da Computação. Participou de grupos de pesquisa pela CAPES. Experiência profissional na HP trabalhando com testes automatizados por 2 anos. Fundador da Quavio Software na Web. Agilista desde 2008 atuando frente a captação e análise de requisitos em diversos projetos de software. Rubista desde 2008 com experiência com vários frameworks web baseados na linguagem. Palestrante em eventos do GURU-RS e GURU-SC – http://www.gururs.org/")},
  {:email => 'rafael.lima@bielsystems.com.br', :name => 'Rafael Lima', :company => 'bielsystems.com.br', :bio => %(Bootstrapper, focado em inovações em tecnologia. Fundador da BielSystems, BUNDLES Brasil e Startup DEV. Desenvolvedor web há 15 anos.)},
  {:email => 'rafael.ssouza@gmail.com', :name => 'Rafael Souza', :company => 'softa.com.br', :bio => %(Mais novo desenvolvedor na Softa. Apaixonado pelo que faz e amante de código bonito. Desenvolve para a web há 10 anos, já usou PHP, Java, .NET e agora programa em Ruby full-time.)},
  {:email => '', :name => 'Rodrigo Flores', :company => 'plataformatec.com.br', :bio => %(Rodrigo Flores (@rlmflores) é graduado em Ciências da Computação pelo IME/USP e desenvolve em Ruby e Rails desde 2009. Ingressou na PlataformaTec em 2010 e desde então conta com diversas boas práticas de desenvolvimento de software para refatorar e sanear códigos legados em projetos críticos (Projects Rescues). Ele estará no RS on Rails para compartilhar suas experiências e dar algumas dicas sobre como manter (ou melhorar) a manutenabilidade de suas aplicações Rails. )},
  {:email => 'gabriel.sobrinho@gmail.com', :name => 'Gabriel Sobrinho', :company => '', :bio => 'Aguardandio bio'},
  {:email => '', :name => 'Thais Camilo', :company => 'hashrocket.com', :bio => 'Aguardandio bio'}]

  def index
    @speakers = SPEAKERS
  end

end